language: php
php:
  - 5.6
  - 5.5
  - 5.4
  - 6.0
  - 6.1
  - 6.2
  - 6.3
  - 6.4
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - hhvm
  - nightly
sudo: false
install:
 - pear config-set preferred_state beta
 - pear install Validate
script:
  - pear run-tests -r tests/
